---
- name: Test Grafana access
  hosts: all
  gather_facts: false
  tasks:
    - name: Wait for Grafana to be accessible on port 3000
      ansible.builtin.uri:
        url: http://{{inventory_hostname}}:3000
        follow_redirects: none
        status_code: [302]
